config/routes.rb
Rails.application.routes.draw do
  resources :allotments
  resources :places
  resources :users do
    collection { post :sort }
  end

  root 'users#index'

  get '/direction_info' => 'users#direction_info', as: :direction_info
  get '/display_list' => 'users#display_list', as: :place_list
  post '/create_allotment' => 'users#create_allotment', as: :create_allotment

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :allotment
	has_many :places
	
	geocoded_by :address   # can also be an IP address
	after_validation :geocode 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @places = Place.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.address
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  
  end

  def display_list
    @allotment = Allotment.new
    session["user_id"] = params[:id]
    if session["user_id"].present?
      @user = User.find(session["user_id"])
      @allotments = @user.allotment.order('position')
      @places_list = @user.places
      if @user.geocoded? && params[:range].present?
        @places = @places_list.near(@user.address, params[:range].to_i, :order => false, :units => :km)  
        if @places.empty?
          @allotments = []
        else
          @allotments.each do |allotment|
            record = @places.where(id: allotment.place_id)
            if record.empty?
              @allotments = @allotments - [allotment]
            end
          end
        end
        @places = @places + [@user] 
      else 
        @places = @places_list + [@user]
      end
      @hash = Gmaps4rails.build_markers(@places) do |place, marker|
        @place = place
        marker.lat place.latitude
        marker.lng place.longitude
        if place.class.name=="Place"
          marker.picture ({:url => ActionController::Base.helpers.asset_path('marker-blue.png'),
                      :width => 32,
                      :height => 32})
          marker.infowindow render_to_string(:action => 'new_allotment', :layout => false)    
          marker.json({ :id => @place.id })
        end
      end
      session["allotment_list"] = @allotments
    end
    respond_to do |format|
      format.js 
    end
  end

  def create_allotment
    @user = User.find(params[:allotment][:user_id])
    @allotments = @user.allotment.order('position')
    @places_list = @user.places
    if @user.geocoded? && params[:range].present?
      @places = @places_list.near(@user.address, params[:range].to_i, :order => false, :units => :km)  
      if @places.empty?
        @allotments = []
      else
        @allotments.each do |allotment|
          record = @places.where(id: allotment.place_id)
          if record.empty?
            @allotments = @allotments - [allotment]
          end
        end
      end
      @places = @places + [@user] 
    else 
      @places = @places_list + [@user]
    end
    @allotment = Allotment.new(allotment_params)
    record = @allotments.find_by_user_id_and_place_id(@allotment.user_id,@allotment.place_id)
    respond_to do |format|
      if !record && @allotment.save
        @allotments = @allotments + [@allotment]
      end
      format.js
    end
  end


  def sort
    @allotment = Allotment.new
    params[:allotment].each_with_index do |id, index|
      Allotment.find(id).update(position: index+1)
    end
    @user = Allotment.find(params[:allotment][0]).user
    @allotments = @user.allotment.order('position')
    @places_list = @user.places
    if @user.geocoded? && params[:range].present?
      @places = @places_list.near(@user.address, params[:range].to_i, :order => false, :units => :km)  
      if @places.empty?
        @allotments = []
      else
        @allotments.each do |allotment|
          record = @places.where(id: allotment.place_id)
          if record.empty?
            @allotments = @allotments - [allotment]
          end
        end
      end
      @places = @places + [@user] 
    else 
      @places = @places_list + [@user]
    end
    session["allotment_list"] = @allotments
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      @place = place
      marker.lat place.latitude
      marker.lng place.longitude
      if place.class.name=="Place"
        marker.picture ({:url => ActionController::Base.helpers.asset_path('marker-blue.png'),
                    :width => 32,
                    :height => 32})
        marker.infowindow render_to_string(:action => 'new_allotment', :layout => false)    
        marker.json({ :id => @place.id })
      end
    end
    respond_to do |format|
      format.js { render "create_allotment.js.erb" }
    end
  end

  def direction_info
    user = User.find(session["user_id"])
    allotment_list = session["allotment_list"]
    if allotment_list.present? && user.present?
      destination =  Place.find(allotment_list.last["place_id"])
      allotment_list = allotment_list - [allotment_list.last]
      waypts=[]
      allotment_list.each_with_index do |allotment,index|
        waypts[index]={
          location:  Place.find(allotment['place_id']).address,
          stopover: true
        }
      end
      @request = {
        origin: user.address,
        destination: destination.address,
        travelMode: params[:travelMode].present? ? params[:travelMode] : "DRIVING",
        waypoints: waypts,
        optimizeWaypoints: true
      }
    else
      @request = {}
    end
    respond_to do |format|
      format.json  { render :json => @request.to_json }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:latitude, :longitude, :name, :address, :title)
    end

    def allotment_params
      params.require(:allotment).permit(:date, :position, :user_id, :place_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_allotment_list.html.erb
<% if @allotments %>
  <table class="table table-striped table-bordered table-hover" id="todo_list" data-update-url="<%= sort_users_url(range: params[:range]) %>">
    <tbody>
      <%= content_tag_for(:tr, @allotments) do |allotment| %>
        <td><%= allotment.place.address if allotment.place.present? %></td>
        <td><%= link_to 'Destroy', allotment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
<% end %>

<script type="text/javascript">
  //question_list jquery
  jQuery(function() {
    return $('#todo_list').sortable({
      axis: 'y',
      items: 'tr',
      cursor: 'crosshair',
      opacity: 0.4,
      scroll: true,
      update: function() {
        return $.post($(this).data('update-url'), $(this).sortable('serialize'));
      }
    });
  });
</script>

app/views/users/_display_list.html.erb
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <%= content_tag_for(:tr, @places_list) do |place| %>
            <td>
                <%= place.name %>
            </td>
            <td>
                <%= place.address %>
            </td>
            <td>
                <%= link_to 'Show', users_path %>
            </td>
            <td>
                <%= link_to 'Edit', edit_place_path(place) %>
            </td>
            <td>
                <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
            <% end %>
    </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :latitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/create_allotment.js.erb
$('#allotment_list').html("<%= escape_javascript (render partial: 'users/allotment_list') %>");
(function() {
  if(!$("#direction").is(':checked')){
  	var markersData = <%= raw @hash.to_json %>;
	updateMarkers(mapHandler, markersData);
  }else{
	var directionsService = new google.maps.DirectionsService();
	$.ajax({
	    url: "<%= direction_info_path %>",
	    type: "GET",
	    dataType: 'JSON',
	    success: function(data) {
	        request = data;
	        directionsService.route(request, function(response, status) {
	            if (status == google.maps.DirectionsStatus.OK) {
	                directionsDisplay.setDirections(response);
	            }
	        });
	        mapHandler.buildMap({
	            provider: {},
	            internal: {
	                id: 'map'
	            }
	        }, function() {
	            directionsDisplay.setMap(mapHandler.getMap());
	        });
	    }
	});
  }
})();

app/views/users/display_list.js.erb
$("#place_list").html("<%= escape_javascript (render partial: 'display_list') %>");
$("#allotment_list").html("<%= escape_javascript (render partial: 'allotment_list') %>");
(function() {
  if(!$("#direction").is(':checked')){
  	var markersData = <%= raw @hash.to_json %>;
	updateMarkers(mapHandler, markersData);
  }else{
  	var directionsService = new google.maps.DirectionsService();
	$.ajax({
	    url: "<%= direction_info_path %>",
	    type: "GET",
	    dataType: 'JSON',
	    success: function(data) {
	        request = data;
	        directionsService.route(request, function(response, status) {
	            if (status == google.maps.DirectionsStatus.OK) {
	                directionsDisplay.setDirections(response);
	            }
	        });
	        mapHandler.buildMap({
	            provider: {},
	            internal: {
	                id: 'map'
	            }
	        }, function() {
	            directionsDisplay.setMap(mapHandler.getMap());
	        });
	    }
	});
  }
})();

app/views/users/edit.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @user, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing user</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="page-header">
    <%= link_to new_user_path, class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-plus"></span> New User
        <% end %>
            <%= link_to new_place_path, class: 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-plus"></span> New Place
                <% end %>
                    <h1>Listing users</h1>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <%= content_tag_for(:tr, @users) do |user| %>
                <td>
                    <a class="user_name" data-id="<%= user.id %>">
                        <%= user.name %>
                            <a></td>
                <td>
                    <%= user.address %>
                </td>
                <td>
                    <%= link_to 'Show', user %>
                </td>
                <td>
                    <%= link_to 'Edit', edit_user_path(user) %>
                </td>
                <td>
                    <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
                <% end %>
        </tbody>
    </table>
</div>
<div class="row">
    <input type="range" id="myRange" value="5" min="0" max="100">
    <b><span id="range_value">5 Km</span></b>
</div>
<div class="row">
    <div id="right-panel"></div>
    <div id="map" style='width: 885px; height: 500px;'></div>
</div>
<div class="row">
    <div id="direction_option" class="hide">
        <select id="mode">
          <option value="DRIVING">Driving</option>
          <option value="WALKING">Walking</option>
          <option value="BICYCLING">Bicycling</option>
          <option value="TRANSIT">Transit</option>
        </select> Mode Of Travelling
        <input type="checkbox" id="direction">Direction
    </div>
</div>
<div class="row">
    <div class="col-md-9" id="place_list">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <%= content_tag_for(:tr, @places) do |place| %>
                    <td>
                        <%= place.name %>
                    </td>
                    <td>
                        <%= place.address %>
                    </td>
                    <td>
                        <%= link_to 'Show', place %>
                    </td>
                    <td>
                        <%= link_to 'Edit', edit_place_path(place) %>
                    </td>
                    <td>
                        <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                    <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-md-3" id="allotment_list">
        <%= render 'allotment_list' %>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        directionsDisplay = new google.maps.DirectionsRenderer();
        var directionsService = new google.maps.DirectionsService();
        var request, __markers;

        $('.user_name').unbind('click');
        $('.user_name').click(function() {
            $('#direction_option').removeClass("hide");
            localStorage.setItem("user_id", $(this).attr("data-id"));
            retrive_place();
        });

        $('#myRange').change(function() {
            $('#direction_option').removeClass("hide");
            $('#range_value').text($(this).val() + " Km");
            retrive_place();
            if (!($('#direction').is(':checked'))) {
                mapHandler.removeMarkers(__markers);
            }
        });

        mapHandler = Gmaps.build('Google');
        mapHandler.buildMap({
            provider: {
                // mapTypeId: 'satellite'
            },
            internal: {
                id: 'map'
            }
        }, function() {
            var markersData = <%= raw @hash.to_json %>;
            updateMarkers(mapHandler, markersData);
        });
        mapHandler.fitMapToBounds();

        $('#direction').change(function() {
            if ($(this).is(':checked')) {
                retrive_route();
            }else{
                mapHandler.removeMarkers(__markers);
                directionsDisplay.setDirections({routes: []}); //clear route
                retrive_place()
            }
        });

        function retrive_place(){
            $.ajax({
                url: "<%= place_list_path %>",
                type: "GET",
                data: {
                    id: localStorage.getItem("user_id"),
                    range: $('#myRange').val()
                }
            });
        }

        function retrive_route() {
            $.ajax({
                url: "<%= direction_info_path %>",
                type: "GET",
                dataType: 'JSON',
                data: {
                    travelMode: $('#mode').val()
                },
                success: function(data) {
                    request = data;
                    directionsService.route(request, function(response, status) {
                        if (status == google.maps.DirectionsStatus.OK) {
                            directionsDisplay.setDirections(response);
                        }
                    });
                    mapHandler.buildMap({
                        provider: {},
                        internal: {
                            id: 'map'
                        }
                    }, function() {
                        mapHandler.removeMarkers(__markers);
                        directionsDisplay.setMap(mapHandler.getMap());
                        directionsDisplay.setPanel(document.getElementById('right-panel'));
                    });
                }
            });
        }


       



        // function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        //     var waypts = [];
        //     var user = <%= raw @hash.to_json %>
        //     debugger
        // waypts.push({
        //     location: checkboxArray[i].value,
        //     stopover: true
        // });

        // directionsService.route({
        //     origin: document.getElementById('start').value,
        //     destination: document.getElementById('end').value,
        //     waypoints: waypts,
        //     optimizeWaypoints: true,
        //     travelMode: google.maps.TravelMode.DRIVING
        // }, function(response, status) {
        //     if (status === google.maps.DirectionsStatus.OK) {
        //         directionsDisplay.setDirections(response);
        //         var route = response.routes[0];
        //         var summaryPanel = document.getElementById('directions-panel');
        //         summaryPanel.innerHTML = '';
        //         // For each route, display summary information.
        //         for (var i = 0; i < route.legs.length; i++) {
        //             var routeSegment = i + 1;
        //             summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
        //                 '</b><br>';
        //             summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
        //             summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
        //             summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
        //         }
        //     } else {
        //         window.alert('Directions request failed due to ' + status);
        //     }
        // });
        // }

        // add double click event
        // google.maps.event.addListener(mapHandler.map.serviceObject, 'dblclick', function(event) {            
        //     geocodePoint(event.latLng, function(data) {
        //        console.log(data);
        //     });                        
        // });

        // var geocoder = new google.maps.Geocoder();

        // function geocodePoint(latlng, callback) {

        //     var street_number = ''; 
        //     var route = ''; 
        //     var country = ''; 
        //     var postal_code = ''; 
        //     var city = ''; 
        //     var full_address = '';
        //     var latitude = latlng.lat();
        //     var longitude = latlng.lng();

        //     geocoder.geocode({'latLng': latlng }, function(responses) { 

        //         if (responses && responses.length > 0) {

        //               full_address = responses[0].formatted_address;

        //               responses[0].address_components.forEach(function(el) { 
        //                   el.types.forEach(function(type) { 
        //                       if(type == 'street_number') street_number = el.long_name;  
        //                       if(type == 'route') route = el.long_name; 
        //                       if(type == 'country') country = el.long_name;
        //                       if(type == 'postal_code') postal_code = el.long_name; 
        //                       if(type == 'locality') city = el.long_name; 
        //                   }) 
        //               }); 
        //         }
        //         else {
        //             alert("Could not geocode... :(");
        //         }

        //         callback({
        //             street_number: street_number,
        //             route: route,
        //             postal_code: postal_code,
        //             city : city,
        //             country: country,
        //             latitude: latitude,
        //             longitude: longitude,
        //             full_address:full_address
        //         }); 
        //     }); 
        // }
    });
</script>

app/views/users/new.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New user</h1>
</div>

<%= render 'form' %>

app/views/users/new_allotment.html.erb
<p>
  <strong>Name:</strong> 
  <%= @place.name %>
</p>

<p>
  <strong>Address:</strong> 
  <%= @place.address %>
</p>


<%= form_for(@allotment, url: create_allotment_path, html: { class: "form-horizontal", role: "form" }, remote: true) do |f| %>
  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date, class: "form-control datepicker" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
       <%= f.select :user_id, User.all.collect { |p| [ p.name, p.id ] }%>
    </div>
  </div>
  <%= f.hidden_field :place_id, class: "form-control",  value: @place.id %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Add Location", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_user_path(@user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show user</h1>
</div>

<dl class="dl-horizontal">
  <dt>Latitude:</dt>
  <dd><%= @user.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @user.longitude %></dd>

  <dt>Name:</dt>
  <dd><%= @user.name %></dd>

  <dt>Address:</dt>
  <dd><%= @user.address %></dd>

  <dt>Title:</dt>
  <dd><%= @user.title %></dd>

</dl>