config/routes.rb
Rails.application.routes.draw do
  resources :allotments
  resources :places
  resources :users do
    collection { post :sort }
  end

  root 'users#index'

  get '/direction_info' => 'users#direction_info', as: :direction_info
  get '/display_list' => 'users#display_list', as: :place_list
  post '/create_allotment' => 'users#create_allotment', as: :create_allotment

end

app/models/allotment.rb
class Allotment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  acts_as_list
end

app/controllers/allotments_controller.rb
class AllotmentsController < ApplicationController
  before_action :set_allotment, only: [:show, :edit, :update, :destroy]

  # GET /allotments
  # GET /allotments.json
  def index
    @allotments = Allotment.all
  end

  # GET /allotments/1
  # GET /allotments/1.json
  def show
  end

  # GET /allotments/new
  def new
    @allotment = Allotment.new
  end

  # GET /allotments/1/edit
  def edit
  end

  # POST /allotments
  # POST /allotments.json
  def create
    @allotments = Allotment.all
    @allotment = Allotment.new(allotment_params)

    respond_to do |format|
      if @allotment.save
        format.js
      else
        format.js
      end
    end
  end

  # PATCH/PUT /allotments/1
  # PATCH/PUT /allotments/1.json
  def update
    respond_to do |format|
      if @allotment.update(allotment_params)
        format.html { redirect_to @allotment, notice: 'Allotment was successfully updated.' }
        format.json { render :show, status: :ok, location: @allotment }
      else
        format.html { render :edit }
        format.json { render json: @allotment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allotments/1
  # DELETE /allotments/1.json
  def destroy
    @allotment.destroy
    respond_to do |format|
      format.html { redirect_to allotments_url, notice: 'Allotment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allotment
      @allotment = Allotment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allotment_params
      params.require(:allotment).permit(:date, :position, :user_id, :place_id)
    end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/views/allotments/_form.html.erb
<%= form_for(@allotment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :position, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :place, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :place, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/allotments/edit.html.erb
<div class="page-header">
  <%= link_to allotments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @allotment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing allotment</h1>
</div>

<%= render 'form' %>

app/views/allotments/index.html.erb
<div class="page-header">
  <%= link_to new_allotment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Allotment
  <% end %>
  <h1>Listing allotments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Date</th>
            <th>Position</th>
            <th>User</th>
            <th>Place</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @allotments) do |allotment| %>
            <td><%= allotment.date %></td>
            <td><%= allotment.position %></td>
            <td><%= allotment.user %></td>
            <td><%= allotment.place %></td>
            <td><%= link_to 'Show', allotment %></td>
        <td><%= link_to 'Edit', edit_allotment_path(allotment) %></td>
        <td><%= link_to 'Destroy', allotment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/allotments/new.html.erb
<%= render 'form' %>

app/views/allotments/show.html.erb
<div class="page-header">
  <%= link_to allotments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_allotment_path(@allotment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show allotment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Date:</dt>
  <dd><%= @allotment.date %></dd>

  <dt>Position:</dt>
  <dd><%= @allotment.position %></dd>

  <dt>User:</dt>
  <dd><%= @allotment.user %></dd>

  <dt>Place:</dt>
  <dd><%= @allotment.place %></dd>

</dl>