config/routes.rb
Rails.application.routes.draw do
  resources :allotments
  resources :places
  resources :users do
    collection { post :sort }
  end

  root 'users#index'

  get '/direction_info' => 'users#direction_info', as: :direction_info
  get '/display_list' => 'users#display_list', as: :place_list
  post '/create_allotment' => 'users#create_allotment', as: :create_allotment

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :allotment
  belongs_to :user

  geocoded_by :address   # can also be an IP address
  after_validation :geocode 
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @users = User.all
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:latitude, :longitude, :name, :address, :title, :user_id)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @place.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h4>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :latitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
       <%= f.select :user_id, User.all.collect { |p| [ p.name, p.id ] }%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="page-header">
  <%= link_to places_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @place, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing place</h1>
</div>

<%= render 'form' %>

app/views/places/index.html.erb
<div class="page-header">
  <%= link_to new_place_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Place
  <% end %>
  <%= link_to users_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Display Map
  <% end %>
  <h1>Listing places</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Name</th>
            <th>Address</th>
            <th>Title</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @places) do |place| %>
            <td><%= place.latitude %></td>
            <td><%= place.longitude %></td>
            <td><%= place.name %></td>
            <td><%= place.address %></td>
            <td><%= place.title %></td>
            <td><%= place.user %></td>
            <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/places/new.html.erb
<div class="page-header">
  <%= link_to places_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New place</h1>
</div>

<%= render 'form' %>

app/views/places/show.html.erb
<dl class="dl-horizontal">
  
  <dt>Name:</dt>
  <dd><%= @place.name %></dd>

  <dt>Address:</dt>
  <dd><%= @place.address %></dd>

  <dt>Title:</dt>
  <dd><%= @place.title %></dd>

</dl>
<div>
  <%= link_to "Add",new_allotment_path, class: 'btn btn-default', remote: true %>
    
  <%= link_to "Edit",edit_place_path(@place), class: 'btn btn-primary', remote: true%>

</div>